/**
 * Generates `src/private/iam-actions.generated.ts` from the official AWS
 * Service Reference (https://docs.aws.amazon.com/service-authorization/latest/reference/service-reference.html).
 *
 * The reference is machine-readable and authoritative:
 *   - the list endpoint returns `[{ service, url, modified }]`
 *   - each service url returns `{ Name: "s3", Actions: [{ Name: "GetObject" }] }`
 *
 * We join `${Name}:${Action.Name}` into a string-literal union so that
 * `expectGrant(fn).can("s3:GetObject")` is type-checked. Output is type-only,
 * so it ships in `.d.mts` and is erased from the runtime bundle.
 *
 * Run with `pnpm gen:iam-actions` (Node 22+, native TS execution). Commit the
 * result; the build never hits the network.
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const LIST_URL = "https://servicereference.us-east-1.amazonaws.com/";
const OUT_PATH = fileURLToPath(new URL("../src/private/iam-actions.generated.ts", import.meta.url));
const CONCURRENCY = 20;

interface ServiceListEntry {
  service: string;
  url: string;
  modified?: number;
}

interface ServiceDoc {
  Name: string;
  Actions?: { Name: string }[];
}

async function fetchJson<T>(url: string, attempts = 3): Promise<T> {
  let lastError: unknown;
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url);
      if (!res.ok) {
        throw new Error(`HTTP ${res.status} for ${url}`);
      }
      return (await res.json()) as T;
    } catch (error) {
      lastError = error;
    }
  }
  throw lastError;
}

/** Run `task` over `items` with a bounded number of in-flight promises. */
async function pooled<T, R>(
  items: T[],
  limit: number,
  task: (item: T) => Promise<R>,
): Promise<R[]> {
  const results: R[] = Array.from({ length: items.length });
  let cursor = 0;
  async function worker(): Promise<void> {
    while (cursor < items.length) {
      const index = cursor++;
      results[index] = await task(items[index]);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return results;
}

async function main(): Promise<void> {
  console.error(`Fetching service list from ${LIST_URL} ...`);
  const list = await fetchJson<ServiceListEntry[]>(LIST_URL);
  console.error(`  ${list.length} services`);

  const services = new Set<string>();
  const actions = new Set<string>();
  let failures = 0;

  await pooled(list, CONCURRENCY, async (entry) => {
    try {
      const doc = await fetchJson<ServiceDoc>(entry.url);
      const prefix = doc.Name;
      if (!prefix) {
        return;
      }
      services.add(prefix);
      for (const action of doc.Actions ?? []) {
        if (action.Name) {
          actions.add(`${prefix}:${action.Name}`);
        }
      }
    } catch (error) {
      failures++;
      console.error(`  ! failed ${entry.service}: ${(error as Error).message}`);
    }
  });

  if (failures > 0) {
    throw new Error(
      `${failures} service file(s) failed to fetch; aborting to avoid a partial union`,
    );
  }

  const sortedServices = [...services].sort();
  const sortedActions = [...actions].sort();
  console.error(
    `Collected ${sortedActions.length} actions across ${sortedServices.length} services`,
  );

  const file = render(sortedServices, sortedActions);
  await writeFile(OUT_PATH, file, "utf8");
  console.error(`Wrote ${OUT_PATH}`);
}

function render(servicesList: string[], actionsList: string[]): string {
  const serviceUnion = servicesList.map((s) => `  | ${JSON.stringify(s)}`).join("\n");
  const actionUnion = actionsList.map((a) => `  | ${JSON.stringify(a)}`).join("\n");
  return `// AUTO-GENERATED by scripts/gen-iam-actions.ts — DO NOT EDIT.
// Source: AWS Service Reference (https://servicereference.us-east-1.amazonaws.com/).
// Regenerate with \`pnpm gen:iam-actions\`.
// ${actionsList.length} actions across ${servicesList.length} services.

/** Every AWS IAM service prefix (the part before the \`:\` in an action). */
export type IamService =
${serviceUnion};

/** Every exact \`service:Action\` IAM action string known to AWS. */
export type ExactIamAction =
${actionUnion};
`;
}

await main();
